version: '3.4'
# версия для apache
services:
    backend:
        build: ./backend
        command: php /var/www/server.php
        ports:
            - "8190:8190"
        volumes:
            - ./backend:/var/www
    
    frontend:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d
